### ISSUE TITLE
storybook-addon-performance を入れるのはどうですか

### ISSUE THREAD

**Issue by kmix-39** [inc2734/basis2#1]
CSSフレームワークに storybook あるの助かりますね
パフォーマンス系も入っていると各コンポーネントのチューニングがしやすくなると思うので storybook-addon-performance を入れてみてはどうです？

参考：
https://storybook.js.org/addons/storybook-addon-performance

**Comment by inc2734** [comment]
提案ありがとうございます！Basis2 で React Component つくっているのはあくまで Storybook で表示確認するのにこのほうが簡単だからでして、ユーザーに提供するものという位置づけではないんです…（だからつくりも適当…
なのでこのアドオンは入れなくても良いかな〜と思います。

**Comment by kmix-39** [comment]
なるほど。そうなると要らないですね…。

basis2 は MUI とか Chakra UI のような Component ライブラリにするのかと思ってました。
Close しておきます。

**Comment by inc2734** [comment]
Chakra UI 知らなかったです！これ僕のやりたいことと似ている部分がありそうですね。情報ありがとうございます！
