### ISSUE TITLE
'@storybook/addon-docs/blocks' で警告が出る

### ISSUE THREAD

**Issue by kmix-39** [inc2734/basis2#2]
Storybook v6.3.7 からは '@storybook/addon-docs/blocks' は deprecated になったので

`import { Meta } from '@storybook/addon-docs/blocks';`
は
`import { Meta } from '@storybook/addon-docs'`
にすると直ります。

参考: 
https://github.com/pocka/storybook-addon-designs/issues/120

**Comment by inc2734** [comment]
ありがとうございます！！
